#ifndef __WATERMEAS_SERIAL__
#define __WATERMEAS_SERIAL__

#define SERIAL_COMMAND_LS 48
#define SERIAL_COMMAND_FILE_READ 49
#define SERIAL_COMMAND_INIT_RUN 50
#define SERIAL_COMMAND_END_RUN 51
#define SERIAL_COMMAND_SYNC_TIME 52

#endif //__WATERMEAS_SERIAL__
